#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source the profile on every top-level shell
if [[ "$SHLVL" -eq 1 ]]; then
  source "$DOTFILES/zsh/zprofile"
fi
