#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR}/prezto/init.zsh" ]]; then
  source "${ZDOTDIR}/prezto/init.zsh"
fi

# Customize to your needs...

# Revive old gst alias from OMZ/git
alias gst="git status"

# git update fork
# Merge upstream
function gupf {
    (
    set -e
    local ORIGIN=${1-origin}
    local UPSTREAM=${2-upstream}
    local LBRANCH=`git symbolic-ref --short HEAD`
    local OBRANCH=${3-$LBRANCH}
    local UBRANCH=${4-$OBRANCH}
    git fetch $ORIGIN
    git fetch $UPSTREAM
    git checkout $ORIGIN/$OBRANCH
    git checkout -b merge
    git merge $UPSTREAM/$UBRANCH -m "merge upstream from `git ls-remote --get-url $UPSTREAM`"
    git checkout $LBRANCH
    git rebase merge
    git branch -d merge
    )
}

# Local overrides
[[ -e "$DOTFILES/zsh/zshrc.local" ]] && source "$DOTFILES/zsh/zshrc.local"
